#ifndef ENGINEERING_CALC_CONSTANTS_H
#define ENGINEERING_CALC_CONSTANTS_H

#define MAX_VAR_NAME_SIZE 50
#define MAX_EXPR_SIZE 256
#define MAX_RPN_SIZE 1024
#define MAX_ELEMENT_SIZE 256


#endif //ENGINEERING_CALC_CONSTANTS_H
